"""Flat tag board: a vertical strip of tags on a rigid backing (foam board, box face).

Instances are generated by ``asset/tag_creation/print_tag_board.py``.

WHY A SEPARATE TYPE FROM PaperSheetConfig. The paper sheet is a landscape page
whose body frame is the TAG frame (x=right, y=down, z=into-paper, rot=identity)
— natural for a wall of tags printed by the page. A board is mounted UPRIGHT and
its long axis is the meaningful one, so its body frame is:

    +x = UP   (toward the first/top tag)
    +y = RIGHT (as seen by a viewer facing the board)
    +z = INTO the board  (the front face normal is -z, like the tags)

Right-handed, and z is shared with the tag frame, so the only difference from a
paper sheet is a 90 deg roll about z. Each tag therefore carries an explicit
rotation (columns = tag axes in board coordinates):

    tag x (right) = board +y  -> (0, 1, 0)
    tag y (down)  = board -x  -> (-1, 0, 0)
    tag z (into)  = board +z  -> (0, 0, 1)

That single constant is `TAG_ROT_X_UP` below; every generated instance uses it,
so "x-axis up" is one shared fact rather than a per-file convention that can
drift.

Tag pitch is `tag_size + gap_m`; the strip is centred on the body origin, so a
3-tag board puts the middle tag exactly at the origin and the outer two at
+/- pitch. `tag_size` is black-border-to-black-border (the same definition the
detector and every other body in this package use); `margin_m` is the white
backing around the strip and only affects the board outline / mesh.
"""
import importlib
import os
import pkgutil
import sys
from dataclasses import dataclass
from typing import Dict

import numpy as np
import trimesh

if __name__ == "__main__":
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from tagged_rigid_body import MeshEntry, TaggedRigidBodyConfig

# Tag frame expressed in the x-up board frame (columns = tag x, y, z).
TAG_ROT_X_UP = [[0.0, -1.0, 0.0],
                [1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0]]


@dataclass(eq=False)
class TagBoardConfig(TaggedRigidBodyConfig):
    """A vertical strip of equally-spaced tags on a flat rigid backing."""
    name: str = "tag_board"
    n_tags: int = 3
    gap_m: float = 0.010          # white gap between adjacent tag black borders
    margin_m: float = 0.010       # backing margin around the strip
    thickness_m: float = 0.003    # backing thickness (foam board / box wall)

    @property
    def width_m(self) -> float:
        return self.tag_size + 2 * self.margin_m

    @property
    def height_m(self) -> float:
        return (self.n_tags * self.tag_size
                + (self.n_tags - 1) * self.gap_m
                + 2 * self.margin_m)

    def get_mesh_entries(self) -> Dict[str, MeshEntry]:
        """Backing slab, sized from the tag geometry. Board frame is x=up,
        y=right, z=into-board, so the box extents are (height, width, thickness)
        in that order — NOT (width, height, …) as a page-framed body would use."""
        mesh = trimesh.creation.box([self.height_m, self.width_m, self.thickness_m])
        mesh.visual.vertex_colors = [245, 245, 245, 255]
        return {"body": MeshEntry(
            key=f"tag_board_mesh_{self.name}",
            # centre of the slab sits half a thickness BEHIND the tag plane (+z is into)
            mesh=mesh, pos=np.array([0.0, 0.0, self.thickness_m / 2.0]), rot=np.eye(3),
        )}


# Auto-discover instances from sibling .py files (same contract as paper_sheet).
ALL_CONFIGS = []
for mod_info in pkgutil.iter_modules(__path__):
    mod = importlib.import_module(f".{mod_info.name}", __name__)
    if hasattr(mod, 'cfg'):
        ALL_CONFIGS.append(mod.cfg)
