"""Auto-generated by asset/tag_creation/print_tag_board.py — do not hand-edit.

Board "box_3": 3 x tag36h11 tags, 50 mm, 10 mm gaps,
10 mm margin. Body frame is x-UP (see tagged_bodies/tag_board);
ids run top -> bottom, so tag_32 is the TOP one.
"""
import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from tagged_bodies.tag_board import TAG_ROT_X_UP, TagBoardConfig
from tagged_rigid_body import TagConfig, verify_bodies

cfg = TagBoardConfig(
    name="box_3",
    n_tags=3,
    tag_size=0.0500,
    gap_m=0.0100,
    margin_m=0.0100,
    tag_family="tag36h11",
    tags={
        "tag_32": TagConfig(id=32, pos=[0.060000, 0.000000, -0.000300], rot=TAG_ROT_X_UP),
        "tag_33": TagConfig(id=33, pos=[0.000000, 0.000000, -0.000300], rot=TAG_ROT_X_UP),
        "tag_34": TagConfig(id=34, pos=[-0.060000, 0.000000, -0.000300], rot=TAG_ROT_X_UP),
    },
)

if __name__ == "__main__":
    verify_bodies(cfg)
