"""Hand-maintained instance (was auto-generated by print_table_tags.py, now stale).

Table "lab_table_b": 1200 x 600 x 30 mm slab, 4 x tag36h11 stickers (50 mm black,
60 mm sticker) on the top surface. Same geometry and tag layout as lab_table_a;
only the tag ids differ (535-538 vs 531-534).

Body frame (see tagged_bodies/table/__init__.py): origin at the TOP-SURFACE
centre, +x along the length (1200 mm), +y along the width (600 mm), +z up. The
four tags lie flat 5 mm ABOVE the top surface (pos z = +0.005; they stand proud
of the slab), tag +x along +y, tag z = -z (down toward the slab).
The inner two sit at y = -0.090 (x = -/+0.060); the outer two are pushed out to
x = -/+0.240 and toward the -y long edge at y = -0.210 (their 30 mm sticker edge
lands 60 mm from that edge). tag_size 50 mm, border 5 mm/side -> 60 mm sticker.
"""
import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from tagged_bodies.table import TAG_ROLLS, TableConfig
from tagged_rigid_body import TagConfig, verify_bodies

TAG_ROLL = TAG_ROLLS["flat_on_top_x_along_y"]

cfg = TableConfig(
    name="lab_table_b",
    length_m=1.2000,
    width_m=0.6000,
    thickness_m=0.0300,
    tag_size=0.0500,
    tag_border_size=0.0050,
    tag_family="tag36h11",
    tag_roll="flat_on_top_x_along_y",
    # Hand-stuck stickers have mm-level placement error; loosen RANSAC so a slightly
    # off tag is not rejected as an outlier (printed cubes keep the tight defaults).
    ransac_reproj_error=8.0,     # px (default 3.0)
    ransac_iterations=200,       # more iterations to cover the larger solution space
    ransac_min_inlier_tags=2,    # need >=2 tags to agree (a single coplanar tag can't pin the far origin)
    planar_solve=True,           # coplanar tags: IPPE + keep the camera-facing branch (kills the flip)
    tags={
        # Outer two: x = -/+0.240 (60 mm out from origin), y = -0.210 (toward the -Y
        # edge); inner two (536/537) unchanged at y = -0.090.
        "tag_535": TagConfig(id=535, pos=[-0.240, -0.210, 0.005], rot=TAG_ROLL),
        "tag_536": TagConfig(id=536, pos=[-0.060, -0.090, 0.005], rot=TAG_ROLL),
        "tag_537": TagConfig(id=537, pos=[ 0.060, -0.090, 0.005], rot=TAG_ROLL),
        "tag_538": TagConfig(id=538, pos=[ 0.240, -0.210, 0.005], rot=TAG_ROLL),
    },
)

if __name__ == "__main__":
    verify_bodies(cfg)
