"""Flat paper sheet body type. Instances generated by print_apriltags.py."""
import importlib
import pkgutil
import numpy as np
import trimesh
import sys
import os
from typing import Dict
from dataclasses import dataclass

if __name__ == "__main__":
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from tagged_rigid_body import TaggedRigidBodyConfig, TagConfig, MeshEntry

@dataclass(eq=False)
class PaperSheetConfig(TaggedRigidBodyConfig):
    """Config for a flat paper sheet with tags.
    Can also represent multiple physical sheets aligned horizontally (e.g., on a wall).
    """
    name: str = "paper_sheet"
    width_m: float = 0.2159  # US Letter width
    height_m: float = 0.2794 # US Letter height
    tag_size: float = 0.1

    def get_mesh_entries(self) -> Dict[str, MeshEntry]:
        """Generate a flat box mesh for the paper.
        Body frame: x=right, y=down, z=into-paper (aligned with tag frame, rot=identity).
        """
        mesh = trimesh.creation.box([self.width_m, self.height_m, 0.0005])
        mesh.visual.vertex_colors = [245, 245, 245, 255] # White paper
        return {"body": MeshEntry(
            key=f"paper_mesh_{self.name}",
            mesh=mesh, pos=np.zeros(3), rot=np.eye(3),
        )}


# Auto-discover instances from sibling .py files
ALL_CONFIGS = []
for mod_info in pkgutil.iter_modules(__path__):
    mod = importlib.import_module(f".{mod_info.name}", __name__)
    if hasattr(mod, 'cfg'):
        ALL_CONFIGS.append(mod.cfg)
